version: '3'

services:
  traefik:
    image: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - certs-volume:/certs
    command: --web --web.metrics.prometheus --web.metrics.prometheus.buckets="0.1,0.3,1.2,5.0" --docker --loglevel=DEBUG
    networks:
      - proxy 
      - internal
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    restart: always
    cap_drop:
      - all
    cap_add:
      - net_bind_service
  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --no-auth --host=unix:///var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:www.atoulou.se,atoulou.se;PathPrefixStrip:/portainer"
      - "traefik.docker.network=proxy"
      - "traefik.port=9000"
    restart: always
    networks:
      - proxy
      - internal 
  letsencrypt-cron:
    labels:
      - "traefik.enable=true"
      - "traefik.backend=letsencrypt-cron"
      - "traefik.frontend.rule=Host:atoulou.se,www.atoulou.se,irc.atoulou.se;PathPrefix:/.well-known/acme-challenge"
      - "traefik.docker.network=proxy"
      - "traefik.port=80"
    image: henridwyer/docker-letsencrypt-cron
    volumes:
      - certs-volume:/certs
    restart: always
    environment:
      DOMAINS: atoulou.se www.atoulou.se irc.atoulou.se
      EMAIL: andrew@atoulou.se
      CONCAT: 0
      SEPARATE: 0
    networks:
      - proxy
    depends_on:
      - traefik
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup
  mysql:
    image: mariadb:latest
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - internal
  adminer: 
    image: adminer:latest 
    networks: 
      - internal 
    ports: 
      - 9001:8080 
    depends_on: 
      - mysql
  wordpress:
    labels:
      - "traefik.enable=true"
      - "traefik.backend=wordpress"
      - "traefik.frontend.rule=Host:www.atoulou.se,atoulou.se"
      - "traefik.docker.network=proxy"
      - "traefik.port=80"
    image: wordpress:php7.1
    volumes:
      - wp-volume:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
    networks:
      - internal
      - proxy
    depends_on:
      - traefik
      - mysql
  ldap:
    image: dinkel/openldap
    volumes:
      - ldap-data-volume:/var/lib/ldap/
      - ldap-config-volume:/etc/ldap/
    environment:
      SLAPD_DOMAIN: ldap.atoulou.se
      SLAPD_ORGANIZATION: Atoulouse
      SLAPD_ADDITIONAL_MODULES: memberof 
    networks:
      - internal
  phpldapadmin:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: 0
      PHPLDAPADMIN_LDAP_CLIENT_TLS: 0
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'ldap': [{'server': [{'tls': False}]},{'login': [{'bind_id': 'cn=admin,dc=ldap,dc=atoulou,dc=se'}]}]},]"
    networks: 
      - internal
    ports:
      - 80
  lounge:
    labels:
      - "traefik.enable=true"
      - "traefik.backend=lounge"
      - "traefik.frontend.rule=Host:irc.atoulou.se"
      - "traefik.docker.network=proxy"
      - "traefik.port=9000"
    image: thelounge/lounge:latest
    volumes:
      - ./state/lounge:/home/lounge/data
    restart: always
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    networks:
      - proxy
    ports:
      - "113:113"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./state/prometheus/:/etc/prometheus/
      - prometheus_volume:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
    depends_on:
      - cadvisor
    networks:
      - proxy
      - internal
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: '-collector.procfs=/host/proc -collector.sysfs=/host/sys -collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)" collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    expose:
      - 9100
    networks:
      - internal
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./state/alertmanager/:/etc/alertmanager/
    networks:
      - internal
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
    networks:
      - internal
  grafana:
    image: grafana/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.backend=grafana"
      - "traefik.frontend.rule=Host:www.atoulou.se,atoulou.se;PathPrefixStrip:/grafana"
      - "traefik.docker.network=proxy"
      - "traefik.port=3000"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_volume:/var/lib/grafana
    environment:
      GF_AUTH_BASIC_ENABLED: "false"
      GF_SERVER_ROOT_URL: https://www.atoulou.se/grafana/
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_PROXY_ENABLED: "true"
    networks:
      - internal
      - proxy
volumes:
  certs-volume:
  db-volume:
  grafana_volume:
  prometheus_volume:
  ldap-data-volume:
  ldap-config-volume:
  wp-volume:
networks:
  internal:
    external: false
  proxy:
    external: true
